### ISSUE TITLE
`overspec` target is not a CMake bug!!!! It's a you bug! ;-p  (I think... maybe I'll eat crow, we'll see...)

### ISSUE THREAD

**Issue by zbeekman** [scivision/fortran-submodule#1]
@scivision, I was curious to see what the CMake problems you were experiencing are. In recent CMakes, you have a problem due to a logic bug in your CMakeLists.txt and/or module naming scheme.

Note: parent.f90 and parent1.f90 both produce modules named `parent.mod`. Since you're dumping all modules into `${CMAKE_BINARY_DIR}` by setting `CMAKE_Fortran_MODULE_DIR` `gfortran` is clobbering module files because they have the same name. If you want to have multiple module files with the same name, you can't be using `-J ..` to the same directory.

**Comment by scivision** [comment]
Ok that's good to know. I will address this soon. Thanks!

**Comment by scivision** [comment]
Hmm, since I wrote that I started using Ninja with CMake, which warns me about that problem right away. Of course I should have known better.

**Comment by scivision** [comment]
fixed, thanks

**Comment by zbeekman** [comment]
@scivision: FYI, the issue with `repeated_child.f90` appears to be a legit CMake bug. I think there's a problem with their parsers to detect modules and submodules. CMake things you're declaring a module in `repeated_child.f90` so it's looking for some variant of `pure.mod` and `real.mod`. The compilation will actually finish correctly, but CMake returns a non-zero exit status from it's module time-stamping.

**Comment by zbeekman** [comment]
(And I suspect a decent work around would be to re-order the *prefix-spec* to start with `real`. BUT, this **IS** a legitimate CMake bug.)

**Comment by zbeekman** [comment]
Yeah, I can confirm that switching from `module real function` to `real module function` and from `module pure real function` to `real module pure function` in `repeated_parent.f90` and `repeated_child.f90` resolves the problem.

**Comment by scivision** [comment]
I just noticed that and was seeing if it was version dependent. happens with 3.12 and 3.16. OK that was the bug I was thinking of.

**Comment by scivision** [comment]
to handle these cases correctly within Meson, I had a little quality time with regex101.com and I think I handled every possible case for module and submodule.

**Comment by zbeekman** [comment]
I'm not super familiar with bison/yacc/flex and parsers. I started poking around at the cmake code/issue but I'm not 100% sure how to contribute. It looks like the C++ sources need to be regenerated and committed as well by running bison. CMake is just looking for where modules are defined and consumed so if you could tell it to ignore

```
MODULE (WORD)* (function|subroutine|procedure) stuff EOSTMT
```

that should do the trick. Basically `MODULE` beginning a statement with (subroutine|function|procedure) in the same statement should be ignored.

**Comment by scivision** [comment]
I since noticed that using CMake with Ninja all these examples work. It's only CMake with GNU Make "Unix Makefiles" or "MinGW Makefiles" that this breaks.
